# Generated by Django 3.0.3 on 2020-02-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn_project', models.CharField(max_length=200)),
                ('dn_originator', models.CharField(max_length=200)),
                ('dn_volume_system', models.CharField(max_length=200)),
                ('dn_type', models.CharField(max_length=200)),
                ('dn_discipline', models.CharField(max_length=200)),
                ('dn_series', models.CharField(max_length=200)),
                ('dn_level', models.CharField(max_length=200)),
                ('dn_zone_sequence', models.CharField(max_length=200)),
                ('drawing_title1', models.CharField(max_length=200)),
                ('drawing_title2', models.CharField(max_length=200)),
                ('drawing_title3', models.CharField(max_length=200)),
            ],
        ),
    ]
