# Generated by Django 3.0.3 on 2020-03-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0004_auto_20200303_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='revision_offset',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='scale',
            field=models.CharField(choices=[('-', '-'), ('1', '1'), ('2', '2'), ('5', '5'), ('10', '10'), ('20', '20'), ('50', '50'), ('100', '100'), ('200', '200'), ('500', '500'), ('1000', '1000'), ('2000', '2000')], default='100', max_length=200),
        ),
    ]
