# Generated by Django 3.0.3 on 2020-03-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0006_auto_20200303_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='drawings',
            options={'verbose_name_plural': 'Drawings'},
        ),
    ]
