# Generated by Django 3.0.3 on 2020-03-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0008_auto_20200303_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissions',
            options={'verbose_name_plural': 'Submissions'},
        ),
    ]
