# Generated by Django 3.0.3 on 2020-03-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0009_auto_20200303_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='req_drawings',
            new_name='all_drawings',
        ),
    ]
