# Generated by Django 3.0.3 on 2020-03-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0010_auto_20200303_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissions',
            old_name='all_drawings',
            new_name='req_drawings',
        ),
        migrations.AddField(
            model_name='drawings',
            name='req_submissions',
            field=models.ManyToManyField(to='drawingregister.Submissions'),
        ),
    ]
