# Generated by Django 3.0.3 on 2020-03-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0011_auto_20200303_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='dn_discipline',
            field=models.CharField(max_length=200, verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_level',
            field=models.CharField(max_length=200, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_originator',
            field=models.CharField(max_length=200, verbose_name='Originator'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_project',
            field=models.CharField(max_length=200, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_series',
            field=models.CharField(max_length=200, verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_type',
            field=models.CharField(max_length=200, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_volume_system',
            field=models.CharField(max_length=200, verbose_name='Volume or System'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_zone_sequence',
            field=models.CharField(max_length=200, verbose_name='Zone or Sequence'),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='req_submissions',
            field=models.ManyToManyField(blank=True, to='drawingregister.Submissions'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='req_drawings',
            field=models.ManyToManyField(blank=True, to='drawingregister.Drawings'),
        ),
    ]
