# Generated by Django 3.0.3 on 2020-03-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0012_auto_20200303_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawings',
            name='req_submissions',
        ),
        migrations.AlterField(
            model_name='submissions',
            name='req_drawings',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='drawingregister.Drawings'),
        ),
    ]
