# Generated by Django 3.0.3 on 2020-03-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0013_auto_20200303_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawings',
            name='drawing_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
