# Generated by Django 3.0.3 on 2020-03-17 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0015_submissions_tobesubmitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='toBeSubmitted',
        ),
    ]
