# Generated by Django 3.0.3 on 2020-03-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0016_remove_submissions_tobesubmitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='file_path',
            field=models.CharField(default='', max_length=500),
        ),
    ]
