# Generated by Django 3.0.3 on 2020-03-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0017_submissions_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
