# Generated by Django 3.0.3 on 2020-03-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0018_auto_20200317_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='was_submitted',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
