# Generated by Django 3.0.3 on 2020-03-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0020_submissions_sub_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='sub_dubspace',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='submissions',
            name='sub_incomplete',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='submissions',
            name='sub_nomatch',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='sub_comp',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
