# Generated by Django 3.0.3 on 2020-03-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0021_auto_20200324_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='sub_comp',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='sub_dubspace',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='sub_incomplete',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='sub_nomatch',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
