# Generated by Django 3.0.3 on 2020-03-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0022_auto_20200324_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='req_drawings',
            field=models.ManyToManyField(blank=True, related_name='submissions', related_query_name='req_submissions', to='drawingregister.Drawings'),
        ),
    ]
