# Generated by Django 3.0.3 on 2020-03-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0023_auto_20200324_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(choices=[('Sydney', 'Sydney'), ('Melborune', 'Melborune'), ('Perth', 'Perth'), ('Brisbane', 'Brisbane'), ('Canberra', 'Canberra'), ('Adelaide', 'Adelaide'), ('International', 'International')], max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['number'],
            },
        ),
        migrations.AlterField(
            model_name='submissions',
            name='req_drawings',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='drawingregister.Drawings'),
        ),
    ]
