# Generated by Django 3.0.3 on 2020-03-25 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0025_drawings_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drawingregister.Projects'),
            preserve_default=False,
        ),
    ]
