# Generated by Django 3.0.3 on 2020-03-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0026_submissions_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='drawing_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
