# Generated by Django 3.0.3 on 2020-03-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0027_auto_20200327_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='sub_date',
            field=models.IntegerField(unique=True),
        ),
    ]
