# Generated by Django 3.0.3 on 2020-03-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0029_auto_20200331_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='sub_date',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='submissions',
            unique_together={('sub_date', 'project')},
        ),
    ]
