# Generated by Django 3.0.3 on 2020-03-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0030_auto_20200331_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawings',
            name='data_store',
            field=models.TextField(default='{}', max_length=9999),
        ),
    ]
