# Generated by Django 3.0.3 on 2020-04-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0031_drawings_data_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='sub_comp',
        ),
        migrations.AddField(
            model_name='submissions',
            name='sub_comp',
            field=models.ManyToManyField(blank=True, related_name='submissions_comp', to='drawingregister.Drawings'),
        ),
    ]
