# Generated by Django 3.0.3 on 2020-04-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0032_auto_20200401_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='was_submitted',
        ),
        migrations.AddField(
            model_name='submissions',
            name='was_submitted',
            field=models.ManyToManyField(blank=True, related_name='submissions_was_sub', to='drawingregister.Drawings'),
        ),
    ]
