# Generated by Django 3.0.3 on 2020-04-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0033_auto_20200401_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='dn_project',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
