# Generated by Django 3.0.3 on 2020-04-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0034_auto_20200401_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='dn_discipline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_originator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_series',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_volume_system',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drawings',
            name='dn_zone_sequence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
