# Generated by Django 3.0.3 on 2020-04-01 04:01

from django.db import migrations, models
import drawingregister.models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0035_auto_20200401_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='parentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', drawingregister.models.DataField(blank=True, default={}, max_length=9999)),
            ],
        ),
        migrations.AlterField(
            model_name='drawings',
            name='data_store',
            field=drawingregister.models.DataField(blank=True, default={}, max_length=9999, verbose_name="{'Test':'test'}"),
        ),
    ]
