# Generated by Django 3.0.3 on 2020-04-01 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0038_auto_20200401_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drawingregister.Projects'),
        ),
    ]
