# Generated by Django 3.0.3 on 2020-04-01 04:20

from django.db import migrations
import drawingregister.models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0040_auto_20200401_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='data_store',
            field=drawingregister.models.DataField(blank=True, default={}, max_length=9999),
        ),
    ]
