# Generated by Django 3.0.3 on 2020-04-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0044_auto_20200401_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='namingConv',
            field=models.TextField(default='[]', max_length=9999),
        ),
    ]
