# Generated by Django 3.0.3 on 2020-04-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0045_auto_20200401_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='namingFunc',
            field=models.TextField(default='[]', max_length=9999),
        ),
    ]
