# Generated by Django 3.0.3 on 2020-04-03 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0046_projects_namingfunc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='namingFunc',
            new_name='namingLUTs',
        ),
    ]
