# Generated by Django 3.0.3 on 2020-04-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawingregister', '0047_auto_20200403_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawings',
            options={'ordering': ['drawing_name'], 'verbose_name_plural': 'Drawings'},
        ),
    ]
