# Generated by Django 3.0.3 on 2020-02-19 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200219_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 8, 59, 14, 661760), verbose_name='date published'),
        ),
    ]
