# Generated by Django 3.0.3 on 2020-02-19 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200220_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 9, 40, 33, 108242), verbose_name='date published'),
        ),
    ]
