# Generated by Django 3.0.3 on 2020-02-19 22:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200220_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 9, 41, 19, 281248), verbose_name='date published'),
        ),
    ]
