# Generated by Django 3.0.3 on 2020-02-19 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200220_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 10, 3, 16, 404335), verbose_name='date published'),
        ),
    ]
