# Generated by Django 3.0.3 on 2020-02-20 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200221_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 9, 24, 3, 739206), verbose_name='date published'),
        ),
    ]
