# Generated by Django 3.0.3 on 2020-02-20 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200221_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 10, 37, 43, 679515), verbose_name='date published'),
        ),
    ]
