# Generated by Django 3.0.3 on 2020-02-21 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200221_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialseries',
            name='series_order',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 11, 20, 54, 863044), verbose_name='date published'),
        ),
    ]
