# Generated by Django 3.0.3 on 2020-02-28 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200228_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 16, 26, 38, 741538), verbose_name='date published'),
        ),
    ]
