# Generated by Django 3.0.3 on 2020-03-02 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200303_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 10, 24, 31, 511146), verbose_name='date published'),
        ),
    ]
