# Generated by Django 3.0.3 on 2020-03-02 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200303_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 10, 57, 56, 134021), verbose_name='date published'),
        ),
    ]
