# Generated by Django 3.0.3 on 2020-03-03 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200303_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 11, 28, 59, 287296), verbose_name='date published'),
        ),
    ]
