# Generated by Django 3.0.3 on 2020-03-03 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200303_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 14, 18, 22, 430096), verbose_name='date published'),
        ),
    ]
