# Generated by Django 3.0.3 on 2020-03-04 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200303_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 15, 21, 1, 577987), verbose_name='date published'),
        ),
    ]
