# Generated by Django 3.0.3 on 2020-03-17 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20200304_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 12, 31, 3, 389088), verbose_name='date published'),
        ),
    ]
