# Generated by Django 3.0.3 on 2020-03-17 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20200317_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 9, 21, 45, 464751), verbose_name='date published'),
        ),
    ]
