# Generated by Django 3.0.3 on 2020-03-24 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20200318_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 14, 5, 11, 951351), verbose_name='date published'),
        ),
    ]
