# Generated by Django 3.0.3 on 2020-03-24 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20200324_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 15, 0, 32, 858177), verbose_name='date published'),
        ),
    ]
