# Generated by Django 3.0.3 on 2020-03-25 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20200325_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 15, 12, 32, 310080), verbose_name='date published'),
        ),
    ]
