# Generated by Django 3.0.3 on 2020-03-31 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20200327_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 11, 3, 16, 792060), verbose_name='date published'),
        ),
    ]
