# Generated by Django 3.0.3 on 2020-03-31 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20200331_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 11, 45, 45, 637617), verbose_name='date published'),
        ),
    ]
