# Generated by Django 3.0.3 on 2020-03-31 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20200331_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 16, 49, 31, 328242), verbose_name='date published'),
        ),
    ]
