# Generated by Django 3.0.3 on 2020-03-31 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20200331_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 9, 45, 19, 274602), verbose_name='date published'),
        ),
    ]
