# Generated by Django 3.0.3 on 2020-04-01 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20200401_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 12, 0, 38, 898882), verbose_name='date published'),
        ),
    ]
