# Generated by Django 3.0.3 on 2020-04-01 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20200401_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 14, 43, 3, 296233), verbose_name='date published'),
        ),
    ]
