# Generated by Django 3.0.3 on 2020-04-01 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20200401_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 14, 46, 33, 687731), verbose_name='date published'),
        ),
    ]
