# Generated by Django 3.0.3 on 2020-04-02 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_auto_20200401_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 10, 24, 37, 971449), verbose_name='date published'),
        ),
    ]
