# Generated by Django 3.0.3 on 2020-04-15 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_auto_20200408_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 12, 49, 49, 82421), verbose_name='date published'),
        ),
    ]
