# Generated by Django 3.0.3 on 2020-04-22 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_auto_20200415_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 14, 25, 19, 585148), verbose_name='date published'),
        ),
    ]
